name: ThirstforWater
version: 2.0.2
main: thirstforwater.thirstforwater.Thirstforwater
api-version: 1.16
authors: [HolyGolf]
description: This plugin adds a thirst and drink system.
website: https://github.com/HolyGolf
softdepend: [PlaceholderAPI]
commands:
  tfw:
    description: Help command
    usage: /<command>
  tfw help:
    description: Help command
    usage: /<command>
  tfw settings:
    description: Settings command
    usage: /<command>
    permission: Thirstforwater.tfw.settings
  tfw reload:
    description: Reload command
    usage: /<command>
    permission: Thirstforwater.tfw.reload
  tfw vip:
    description: With this permission, thirst is spent longer (x2 slower)
    usage: /<command>
    permission: Thirstforwater.tfw.vip
  tfw noThirst:
    description: Removing thirst for player
    usage: /<command>
    permission: Thirstforwater.tfw.noThirst