name: ThirstforWater
version: 1.5
main: thirstforwater.thirstforwater.Thirstforwater
api-version: 1.13
authors: [HolyGolf]
description: This plugin adds a thirst and drink system.
website: https://github.com/HolyGolf
softdepend: [PlaceholderAPI]
